### PR TITLE
[CHORE] Adjust code style to personal preferences

### PR DESCRIPTION
**Pull request by kperwel**
- Change to base airbnb,
- add prettier,
- add trasnform-class-properties
- redux debug tools
- expose store to window for debug purposes

### CODE REVIEW

**Comment by kperwel** [comment]
Sorry about that. I've opened PR by mistake. :)

**Comment by edwinwebb** [comment]
Seems like good improvements. Did you rebase your commits?

**Comment by kperwel** [comment]
Any preferences? i can adjust it a bit and open PR again with correct commit message and PR name.
I have to update documentation too.

Yes, i did rebase.

**Comment by edwinwebb** [comment]
I'll take a more detailed look at your work in the next 24 hours. Hope I can take some changes.

**Comment by edwinwebb** [comment]
I like the linting updates you made. I will be taking them to my other projects.

I've made some changes to master since this PR. See the last two PRs I made. I'd be happy to take your work without the class-props transform. Best add some instructions to turn off the linting as it's not going to be to everyones taste. Maybe a link to how to use the dev tools too. 

Would be interested to hear about any other improvements you can suggest and how you get on with the seed.

Thanks in advance.

**Comment by edwinwebb** [comment]
I did it myself

**Pull request closed without merging**
